server:
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
    profiles:
        active: test
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
            timeout: 0
    jpa:
        database: MYSQL
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    mvc:
        view.prefix: classpath:/templates/
        view.suffi: =.html
        static-path-pattern: /static/**