spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8090
---
spring:
  profiles: prod
server:
  port: 8091
---
spring:
  profiles: default
server:
  port: 8080
---

server:
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/liuhao?characterEncoding=UTF-8
        username: root
        password: root
    jpa:
        database: MYSQL
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    mvc:
        view.prefix: classpath:/templates/
        view.suffi: =.html
        static-path-pattern: /static/**
user:
    id: 222
    userName: sdjfskdl
    password: 122112