spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 7090
---
spring:
  profiles: prod
server:
  port: 7091
---
spring:
  profiles: default
server:
  port: 7089
---

server:
    context-path: /springboot-app

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/liuhao?characterEncoding=UTF-8
        username: root
        password: root
    jpa:
        database: MYSQL
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    dubbo:
        application:
            name: springboot-app
        registry:
            address: zookeeper://127.0.0.1:2181
        protocol:
            name: dubbo
            port: 20880
        scan:
            com.liuhao.springboot.demo
